In [3]:
import torch
import torch.nn as nn


# Cross-Entropy Loss


In [4]:
loss_function = nn.CrossEntropyLoss()

In [5]:
target_tensor = torch.tensor([1])
target_tensor

tensor([1])

In [6]:
predection_tensor = torch.tensor([[2.0, 5.0]])
loss_value = loss_function(predection_tensor, target_tensor)
loss_value


tensor(0.0486)

In [7]:
predection_tensor = torch.tensor([[1.5, 1.1]])
loss_value = loss_function(predection_tensor, target_tensor)
loss_value

tensor(0.9130)

# Mean Squared Error Loss


In [8]:
# Define loss function
loss_function = nn.MSELoss()

In [10]:
# Define the prediction and actual values as  tensors
predection_tensor = torch.tensor([32000.0])
actual_tensor = torch.tensor([30000.0])

In [13]:
# Compute the Loss
loss_value = loss_function(predection_tensor, actual_tensor)
print(loss_value.item())
# Loss value: 20000 * 20000 / 1 = 400000000

4000000.0


### PyTorch loss functions are essential tools that help in improving the accuracy of a model by measuring errors. These functions come in different forms to tackle various problems, like deciding between categories (classification) or predicting values (regression). Understanding and using these functions correctly is key to making smart, effective models that do a great job at the tasks they're designed for!

# Technical Terms Explained:
**Loss functions**: They measure how well a model is performing by calculating the difference between the model's predictions and the actual results.

**Cross entropy loss**: This is a measure used when a model needs to choose between categories (like whether an image shows a cat or a dog), and it shows how well the model's predictions align with the actual categories.

**Mean squared error**: This shows the average of the squares of the differences between predicted numbers (like a predicted price) and the actual numbers. It's often used for predicting continuous values rather than categories.

# Code Examples


## ```Cross-Entropy Loss```


In [16]:
import torch
import torch.nn as nn

loss_function = nn.CrossEntropyLoss()

# Our dataset contains a single image of a dog, where
# cat = 0 and dog = 1 (corresponding to index 0 and 1)
target_tensor = torch.tensor([1])
target_tensor
# tensor([1])



tensor([1])

## Prediction: Most likely a dog (index 1 is higher)


In [20]:
# Note that the values do not need to sum to 1
predicted_tensor = torch.tensor([[2.0, 5.0]])
loss_value = loss_function(predicted_tensor, target_tensor)
loss_value
# tensor(0.0181)

C:\Users\KING\AppData\Roaming\Python\Python312\site-packages\torch\nn\modules\loss.py:608: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([1, 2])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


tensor(8.5000)

## Prediction: Slightly more likely a cat (index 0 is higher)

In [18]:
predicted_tensor = torch.tensor([[1.5, 1.1]])
loss_value = loss_function(predicted_tensor, target_tensor)
loss_value
# tensor(0.9130)

tensor(0.9130)

## ```Mean Squared Error Loss```

In [19]:

# Define the loss function
loss_function = nn.MSELoss()

# Define the predicted and actual values as tensors
predicted_tensor = torch.tensor([320000.0])
actual_tensor = torch.tensor([300000.0])

# Compute the MSE loss
loss_value = loss_function(predicted_tensor, actual_tensor)
print(loss_value.item()) # Loss value: 20000 * 20000 / 1 = ...
# 400000000.0

400000000.0


# Resources

[torch.nn.CrossEntropyLoss documentation](https://pytorch.org/docs/stable/generated/torch.nn.CrossEntropyLoss.html#torch.nn.CrossEntropyLoss)

[torch.nn.MSELoss documentation](https://pytorch.org/docs/stable/generated/torch.nn.MSELoss.html#torch.nn.MSELoss)

[Index of PyTorch loss functions](https://pytorch.org/docs/stable/nn.html#loss-functions)